<a href="https://colab.research.google.com/github/anish477/Machine-Learning-/blob/main/Worksheet_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Create a Python program that converts between different units of measurement.

In [ ]:
def conversion():

  try:
    conversion.__doc__
    data=float(input("Enter The value "))
    if(type(data)==float):

      print("Convert meters (m) to feet (ft) =1")
      print("Convert feet (ft) to meters (m) =2")
      print("Convert pounds (lbs) to kilograms (kg) =3")
      print("Convert kilograms (kg) to pounds (lbs) =4")
      print("Convert liters (L) to gallons (gal) =5")
      print("Convert gallons (gal) to liters (L) =6")
      con=int(input("Select conversion "))

      match con:
        case 1:
          print("Convert meters (m) to feet (ft).")
          print(f'converted value is {data*3.28084} ft')
        case 2:
          print("Convert feet (ft) to meters (m)")
          print(f'converted value is {data/3.28084} m')
        case 3:
          print("Convert pounds (lbs) to kilograms (kg)")
          print(f'converted value is {data/2.205} kg')
        case 4:
          print("Convert kilograms (kg) to pounds (lbs)")
          print(f'converted value is {data*2.205} lbs')
        case 5:
          print("Convert liters (L) to gallons (gal)")
          print(f'converted value is {data*0.264172} gal')
        case 6:
          print("Convert gallons (gal) to liters (L)")
          print(f'converted value is {data/0.264172} L')

  except Exception as e:
    print(e)

def doc():
   '''
  This program performs the conversion lengt, weidth, and volume. User input is given by user.
  '''

conversion()






Enter The value 25
Convert meters (m) to feet (ft) =1
Convert feet (ft) to meters (m) =2
Convert pounds (lbs) to kilograms (kg) =3
Convert kilograms (kg) to pounds (lbs) =4
Convert liters (L) to gallons (gal) =5
Convert gallons (gal) to liters (L) =6
Select conversion 2
Convert feet (ft) to meters (m)
converted value is 7.6199997561600075 m


##Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

In [ ]:


def addition(num1,num2):
  print('performing addition')
  return num1+num2

def subtraction(num1,num2):
  print('performing Subtraction')
  return num1-num2
def divison(num1,num2):
  print('performing division')
  return num1/num2

def multiplication(num1,num2):
  print('performing multiplication')
  return num1*num2

def main():
  try:
    num1=input("Enter num 1")
    num2=input("Enter num2")
    cal=input("Give calculatiuon metrics")
    match cal:
      case "+":
        res=addition(num1,num2)
        print(res)
      case'-':
        print(subtraction(num1,num2))
      case'*':
       print(multiplication(num1,num2))
      case'/':
        print(divison(num1,num2))


  except Exception as e:
    print(e)
main()



Enter num 15
Enter num23
Give calculatiuon metrics+
performing addition
53


##4.2 Exercise on List Manipulation:
1. Extract Every Other Element:

In [30]:
def extract_every_other(lst):
  newlist=[]
  for i in range(0,len(lst),2):
      newlist.append(lst[i])
  print(newlist)

lst=[1,2,3,4,5]
extract_every_other(lst)

[1, 3, 5]


###2. Slice a Sublist:

In [34]:
def get_sublist(lst, start, end):
  print(lst[start:end+1])



lst=[1,2,3,4,5]
get_sublist(lst,2,4)


[3, 4, 5]


###3. Reverse a List Using Slicing:

In [37]:
def reverse_list(lst):
  print(lst[::-1])

lst=[1,2,3,4,5]
reverse_list(lst)

[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

In [39]:
def remove_first_last(lst):
  print(lst[1:-1])
lst=[1,2,3,4,5]
remove_first_last(lst)

[2, 3, 4]


Get the First n Elements:

In [46]:
def get_first_n(lst,n):
  print(lst[:n])
lst=[1,2,3,4,5]
n=3
get_first_n(lst,n)

[1, 2, 3]


In [48]:
def get_last_n(lst,n):
  print(lst[-n:])
lst=[1,2,3,4,5]
n=2
get_last_n(lst,n)

[4, 5]


In [66]:
def reverse_skip(lst):
  print(lst[-2::-2])
lst=[1,2,3,4,5,6]
reverse_skip(lst)

[5, 3, 1]


4.3 Exercise on Nested List:

In [86]:
def flatten(lst):
  flatten_list=[]
  for sublist in lst:
    for i in sublist:
      print(i)
      flatten_list.append(i)
  print(flatten_list)


lst=[[1, 2], [3, 4], [5]]
flatten(lst)

1
2
3
4
5
[1, 2, 3, 4, 5]


In [82]:
#2. Accessing Nested List Elements:
def access_nested_element(lst, indices):
  for i in indices:
    lst=lst[i]
  print(f"{lst}")

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices=[1,2]
access_nested_element(lst, indices)

6


In [98]:
def sum_nested(lst):
  sum=0
  for sublist in lst:
    if isinstance(sublist,list):
      sum +=sum_nested(sublist)
    else:
      sum+=sublist
  return sum
lst=[[1, 2], [3, [4, 5]], 6]
sum_nested(lst)

21

In [111]:
def remove_element(lst, elem):
  for sublist in lst:
    for i in sublist:
      if(i==elem):
        sublist.remove(i)


print(lst)

lst = [[1, 2], [3, 2], [4, 5]]
elem=2
remove_element(lst, elem)


[[1], [3], [4, 5]]


In [122]:
def find_max(lst):
  maximum=0
  for sublist in lst:
    if isinstance(sublist,list):
      for item in sublist:
        maximum = max(maximum, find_max(sublist))
    else:
      maximum=max(maximum,sublist)
  return maximum


lst=[[1, 2], [3, [4, 5]], 6]
find_max(lst)

6

In [127]:
def count_element(lst, elem):
  count=0
  for sublist in lst:
    for i in sublist:
      if(i==elem):
        count +=1
  return count


lst = [[1, 2], [2, 3], [2, 4]]
elem=2
count_element(lst, elem)

3

In [142]:
def deep_flatten(lst):
  new_list=[]
  for sublist in lst:
    if isinstance(sublist,list):
      new_list.extend(deep_flatten(sublist))

    else:
      new_list.append(sublist)
  return new_list


lst=[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
deep_flatten(lst)


[1, 2, 3, 4, 5, 6, 7, 8]

In [147]:
def average(lst, elem):
  count=0
  sum=0
  for sublist in lst:
    for i in sublist:
        sum=sum+i
        count +=1


  return sum/count

lst = [[1, 2], [3, 4], [5, 6]]
elem=2
average(lst, elem)

3.5

##6 Getting Started with NumPy:

In [16]:
# 1. Initialize an empty array with size 2X2.
import numpy as np
arr1=np.empty((2,2))
print(arr1)

[[3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323]]


In [9]:
arr=np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
arr=np.full((2,2),7,dtype=int)
print(arr)

[[7 7]
 [7 7]]


In [17]:
arr=np.zeros_like(arr1)
print(arr)

[[0. 0.]
 [0. 0.]]


In [20]:
arr=np.ones_like(arr1)
print(arr)

[[1. 1.]
 [1. 1.]]


In [21]:
new_list = [1,2,3,4]
arr=np.array(new_list)
print(arr)

[1 2 3 4]


In [24]:
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [26]:
mat=np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
arr=np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
arr=np.random.random(30)
mean=arr.mean()
print(mean)

0.5829463407174927


In [35]:
arr=np.random.random(30)
maximum=max(arr)
minimum=min(arr)
print(maximum)
print(minimum)


0.9721859598637511
0.00284756328104363


In [37]:
arr=np.zeros(10)
arr[4]=1
print(arr)



[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
arr = [1, 2, 0, 0, 4, 0]
print(arr[::-1])

[0, 4, 0, 0, 2, 1]


In [44]:
arr=np.ones((3,3))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [56]:
arr=np.zeros((8,8))
arr[1::2, ::2]=1
arr[::2, 1::2] = 1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [78]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print(x+y)
print()
print(x-y)
print()

print(x*2)
print()
print(y*2)
print()
print(np.square(x))
print()
print(np.square(y))
print("\nDot product" )
print(np.dot(v,w))
print("\nDot product x y")
print(np.dot(x,y))
print("\nDot product x v")
print(np.dot(x,v))

[[ 6  8]
 [10 13]]

[[-4 -4]
 [-4 -3]]

[[ 2  4]
 [ 6 10]]

[[10 12]
 [14 16]]

[[ 1  4]
 [ 9 25]]

[[25 36]
 [49 64]]

Dot product
219

Dot product x y
[[19 22]
 [50 58]]

Dot product x v
[29 77]


In [80]:
cat_row=np.concatenate((x,y),axis=0)
print(cat_row)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]


In [81]:
cat_col=np.concatenate((x,y),axis=1)
print(cat_col)

[[1 2 5 6]
 [3 5 7 8]]


In [83]:
cat_row=np.concatenate((x,v),axis=0)
print(cat_row)

#this jhappened beaciuse the demison of the x and v does
#not match as the one is one dimension and another is 2 dimension

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [85]:


A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])


In [92]:

A_inv = np.linalg.inv(A)

result = np.dot(A, A_inv)

I = np.eye(2)

print(result)
print(I)
if np.allclose(result, I):
    print("It is proved.")



[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
[[1. 0.]
 [0. 1.]]
It is proved.


In [97]:
AB = np.dot(A, B)
BA = np.dot(B, A)
if np.array_equal(AB, BA):
  ("it is proved")
else:
    print("not proved")



not proved


In [98]:

AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)

B_T_A_T = np.dot(B_T, A_T)


if np.array_equal(AB_T, B_T_A_T):
  print("It is equal (AB)T = BTAT")
else:
  print("not proved")

It is equal (AB)T = BTAT


In [99]:
A= np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])


A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print(X)

[ 2.  1. -2.]


In [7]:
import time
import numpy as np

size=1000000

list_a = list(range(size))
list_b = list(range(size))

arr_a = np.arange(size)
arr_b = np.arange(size)

start_time = time.time()

start_time = time.time()
list_sum = [a + b for a, b in zip(list_a, list_b)]
list_add_time = time.time() - start_time
print(list_add_time)


start_time = time.time()
np_sum = arr_a + arr_b
np_add_time = time.time() - start_time
print(np_add_time)

0.06766319274902344
0.003030061721801758


In [8]:

start_time = time.time()
list_multiplication = [a * b for a, b in zip(list_a, list_b)]
list_multiplication_time = time.time() - start_time
print(list_multiplication_time)


start_time = time.time()
np_multiplication = arr_a * arr_b
np_multiplication_time = time.time() - start_time
print(np_multiplication_time)

0.13631129264831543
0.0030455589294433594


In [11]:

start_time = time.time()
list_dot_product = sum(a * b for a, b in zip(list_a, list_b))
list_dot_product_time = time.time() - start_time
print(list_dot_product_time)

start_time = time.time()
np_dot_product = np.dot(arr_a, arr_b)
np_dot_product_time = time.time() - start_time
print(np_dot_product_time)

0.08350634574890137
0.0018086433410644531


In [10]:

size_matrix = 1000
matrix_a = [[i for i in range(size_matrix)] for _ in range(size_matrix)]
matrix_b = [[i for i in range(size_matrix)] for _ in range(size_matrix)]

start_time = time.time()
matrix_multiplication_python = [[sum(a * b for a, b in zip(row_a, col_b)) for col_b in zip(*matrix_b)] for row_a in matrix_a]
matrix_multiplication_python_time = time.time() - start_time
print(matrix_multiplication_python_time)

np_matrix_a = np.arange(size_matrix * size_matrix).reshape(size_matrix, size_matrix)
np_matrix_b = np.arange(size_matrix * size_matrix).reshape(size_matrix, size_matrix)

start_time = time.time()
matrix_multiplication_numpy = np.dot(np_matrix_a, np_matrix_b)
matrix_multiplication_numpy_time = time.time() - start_time
print(matrix_multiplication_numpy_time)

159.41729712486267
1.445967674255371
